# http://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html

version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/mecab-ko-dic
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: deploy/application-stop.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: deploy/application-start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: deploy/validate.sh
      timeout: 60
      runas: root